logging: 
  level:
      # 日志级别调整
    root: info
  config: classpath:log4j2-boot-dev.xml
server:
  # 服务对外暴露的端口号
  port: 8080
  servlet:
    context-path: /leaf-demo
spring: 
  application:
    name: bamboo-leaf-demo
  devtools:
    restart:
      enabled: true  #设置开启热部署
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://29.2.231.222:3306/bamboo-leaf?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: deployop
      password: 6r2RaGP4m
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: druid
        login-password: druid
        filter:
          stat:
            enabled: true
            # 慢SQL记录
            log-slow-sql: true
            db-type: mysql
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
bamboo:
  leaf:
    table:
      segmentTableName: bamboo_leaf_segment
      remarkColumnName: remark
    configure:
      retry: 16
      step: 20000
    client:
      leafToken: 0504c00e-7971-41d1-87e8-0952399c5816
      leafServer: 127.0.0.1:8087